server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # cache aset statis
    location ~* \.(css|js|json|png|jpe?g|svg|ico|webp)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_min_length 1024;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
